#!/usr/bin/ruby
# frozen_string_literal: true

default_platform :ios
platform :ios do

  desc "Build the app"
  lane :build do
    gym(
      scheme: "BrewBuddy",
      configuration: "Release",
      export_method: "app-store",
      output_directory: "./build"
    )
  end


end
