#!/usr/bin/ruby
# frozen_string_literal: true

fastlane_version '2.225.0'

default_platform :ios
platform :ios do

  desc "Build the app"
  lane :build do
    # Build the app (code signing should be done separately)
    gym(
      scheme: "BrewBuddy",
      configuration: "Release",
      export_method: "app-store",
      output_directory: "./build",
      export_options: {
        uploadBitcode: false,
        uploadSymbols: true,
        compileBitcode: false
      }
    )
  end

  desc "Run tests"
  lane :test do
    # TODO: Add test target to BrewBuddy scheme first
    # For now, just build to verify compilation
    gym(
      scheme: "BrewBuddy",
      configuration: "Debug",
      export_method: "development",
      output_directory: "./build",
      skip_package_ipa: true
    )
  end

end
