name: Build and Test iOS App

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: macos-latest

    strategy:
      matrix:
        device: ["iPhone 15 Pro", "iPhone SE (3rd generation)"]
      fail-fast: false

    steps:
      - uses: actions/checkout@v4

      # Set up Xcode 16
      - name: Set up Xcode
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: "16.2.0"

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.1
          bundler-cache: true

      - name: Cache Xcode derived data
        uses: actions/cache@v4
        with:
          path: ~/Library/Developer/Xcode/DerivedData
          key: ${{ runner.os }}-xcode-deriveddata-${{ hashFiles('**/*.xcodeproj/project.pbxproj') }}
          restore-keys: |
            ${{ runner.os }}-xcode-deriveddata-

      - name: Install dependencies
        run: bundle install

      # Note: For unit tests, you typically don't need code signing
      # Remove these steps if your tests don't require it

      - name: Run tests
        run: bundle exec fastlane test
        env:
          TEST_DEVICE: ${{ matrix.device }}

      - name: Upload test results
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: test-results-${{ matrix.device }}
          path: |
            fastlane/test_output/
            *.junit

      - name: Upload coverage reports
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: coverage-${{ matrix.device }}
          path: |
            *.xcresult
